name: Create Release on Tag Push

on:
    push:
        branches: [ "dev" ]
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout
            - name: Checkout
              uses: actions/checkout@v3

            # Install Node.js
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: "https://registry.npmjs.org"

            # Install dependencies
            - name: Install dependencies
              uses: borales/actions-yarn@v4
              with:
                  cmd: install
            
            # Build production bundle
            - name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: build

            # Release
            - name: Release
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true
                  artifactErrorsFailBuild: true
                  artifacts: 'package.zip'
                  token: ${{ secrets.GITHUB_TOKEN }}
                  prerelease: true