name: Create Release

on:
    push:
        branches: [ "dev" ]
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout
            - name: Checkout
              uses: actions/checkout@v3

            # Install Node.js
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: "https://registry.npmjs.org"

            # Install dependencies
            - name: Install dependencies
              uses: borales/actions-yarn@v4
              with:
                  cmd: install
            
            # Build production bundle
            - id: build
              name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: build

            # cache
            - name: Cache directory
              uses: actions/cache@v2
              with:
                  path: build
                  key: ${{ runner.os }}-cache-directory-${{ hashFiles('yarn.lock') }}

            # 签出main
            - name: Checkout main
              uses: actions/checkout@v3
              with:
                  ref: main
                  clean: false

            # ls & pwd
            - name: ls & pwd
              run: |
                ls -al
                pwd
                find . ! -path "./build*" -mindepth 1 -delete
                ls -al

            # zip
            - name: Zip build directory
              run: zip -r package.zip build

            # Upload artifact
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: package
                  path: package.zip