name: Create Release on Tag Push

on:
    push:
        branches: [ "dev" ]
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout
            - name: Checkout
              uses: actions/checkout@v3

            # Install Node.js
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: "https://registry.npmjs.org"

            # Install dependencies
            - name: Install dependencies
              uses: borales/actions-yarn@v4
              with:
                  cmd: install
            
            # Build production bundle
            - name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: build

            # zip
            - name: Zip build directory
              run: zip -r package.zip build

            # Upload artifact
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: package
                  path: package.zip