name: Create Release

on:
    push:
        branches: [ "dev" ]
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout
            - name: Checkout
              uses: actions/checkout@v3

            # Install Node.js
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: "https://registry.npmjs.org"

            # Install dependencies
            - name: Install dependencies
              uses: borales/actions-yarn@v4
              with:
                  cmd: install
            
            # Build production bundle
            - id: build
              name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: build
              run: |
                  # 在这里进行构建操作
                  # 假设构建目录为 `dist`
                  echo "::set-output name=build_dir::build"

            # 签出main  如何引用上一个step输出的东西？？
            - name: Checkout main
              uses: actions/checkout@v3
              with:
                  ref: main

            # ls & pwd
            - name: ls & pwd
              run: |
                ls -al
                pwd
                ls -al ${{ steps.build_step.outputs.build_dir }}

            # zip
            - name: Zip build directory
              run: zip -r package.zip build

            # Upload artifact
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: package
                  path: package.zip